Consultado/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
]

webapp/urls.py
from django.urls import path
from . import views
from .views import custom_logout

urlpatterns = [
    path('', views.home_view, name='home'), 
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    
    path('customer-details/', views.customer_details_view, name='customer_details'),
    path('payment-form/', views.payment_form_view, name='payment_form'),
    path('view-payments/',views.view_payments, name='view_payments'),
    path('reservation-form/', views.reservation_form_view, name='reservation_form'),
    path('feedback-form/', views.feedback_form_view, name='feedback_form'),
    path('view-feedback/',views.view_feedback, name='view_feedback'),
    path('logout/', custom_logout, name='custom_logout'),
    path('view-reservations/', views.view_reservations, name='view_reservations'),
    path('view-CustomerDetails/',views.view_CustomerDetails, name='view_CustomerDetails'),
    path('update-reservation/<int:reservation_id>/', views.update_reservation, name='update_reservation'),
    path('cancel_reservation/<int:reservation_id>/', views.cancel_reservation, name='cancel_reservation')
]

webapp/models.py
import datetime
from django.contrib.auth.models import User
from django.db import models

class CustomerDetail(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=30, null=True)
    last_name = models.CharField(max_length=30, null=True)
    address = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=15)
    email = models.EmailField()
    def __str__(self):
        return f"{self.first_name} {self.last_name}'s Details"


class Payment(models.Model):    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    card_number = models.CharField(max_length=16)
    card_expiry = models.DateField(default=datetime.date.today)
    card_cvv = models.CharField(max_length=4, default='')

    def __str__(self):
        return f"Payment info for {self.user.username}"

class Reservation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    check_in_date = models.DateField(default=datetime.date.today)
    check_out_date = models.DateField(default=datetime.date.today)
    ROOM_TYPE_CHOICES = [
        ('single', 'Single'),
        ('double', 'Double'),
        ('suite', 'Suite'),
    ]
    room_type = models.CharField(max_length=50, choices=ROOM_TYPE_CHOICES, default='single')
    num_guests = models.IntegerField(default=1)
    special_requests = models.TextField(default='No special requests')
    
    def __str__(self):
        return f"Reservation for {self.user.username}"

class Feedback(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)
    comments = models.TextField(default='No comments')

    def __str__(self):
        return f"Feedback for {self.user.username}"

webapp/forms.py
from datetime import date
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from .models import Payment, Reservation, Feedback, CustomerDetail

class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = ['card_number', 'card_expiry', 'card_cvv']

class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ['check_in_date', 'check_out_date', 'room_type', 'num_guests', 'special_requests']
        widgets = {
            'check_in_date': forms.DateInput(attrs={'type': 'date'}),
            'check_out_date': forms.DateInput(attrs={'type': 'date'}),
        }
        
class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['rating', 'comments']

class LoginForm(AuthenticationForm):
    class Meta:
        fields = ['username', 'password']

class CustomerDetailsForm(forms.ModelForm):
    class Meta:
        model = CustomerDetail
        fields = ['first_name', 'last_name', 'address', 'phone_number', 'email']

class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

webapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from .forms import PaymentForm, ReservationForm, FeedbackForm, RegistrationForm, CustomerDetailsForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as django_logout
from .models import Reservation, CustomerDetail, Payment, Feedback

def home_view(request):
    return render(request, 'pages/home.html') 

def register_view(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.email = form.cleaned_data['email']
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user.save()
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                
                return redirect('customer_details')
    else:
        form = RegistrationForm()
    
    return render(request, 'pages/registration_form.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                
                return redirect('home')
    else:
        form = AuthenticationForm()
    
    return render(request, 'pages/login.html', {'form': form})

def custom_logout(request):
    django_logout(request)
    return redirect('home')

#RESERVATION INFO
@login_required
def reservation_form_view(request):
    if request.method == 'POST':
        form = ReservationForm(request.POST)
        if form.is_valid():
            reservation = form.save(commit=False)
            reservation.user = request.user  # Set the user to the currently logged-in user
            reservation.save()
            return redirect('home')
    else:
        form = ReservationForm()
    
    return render(request, 'pages/reservation_form.html', {'form': form})


@login_required
def view_reservations(request):
    user_reservations = Reservation.objects.filter(user=request.user)
    return render(request, 'pages/view_reservations.html', {'user_reservations': user_reservations})

@login_required
def update_reservation(request, reservation_id):
    reservation = get_object_or_404(Reservation, pk=reservation_id, user=request.user)

    if request.method == 'POST':
        form = ReservationForm(request.POST, instance=reservation)
        if form.is_valid():
            form.save()
            return redirect('view_reservations')  # Redirect to view reservations after updating
    else:
        form = ReservationForm(instance=reservation)
    
    return render(request, 'pages/update_reservation.html', {'form': form})

@login_required
def cancel_reservation(request, reservation_id):
    reservation = get_object_or_404(Reservation, pk=reservation_id, user=request.user)
    
    if request.method == 'POST':
        
        reservation.delete()
        return redirect('view_reservations')  # Redirect to view reservations after cancellation
    

    return redirect('view_reservations')




#PAYMENT INFO
@login_required
def payment_form_view(request):
    if request.method == 'POST':
        form = PaymentForm(request.POST)
        if form.is_valid():
            Payment = form.save(commit=False)
            Payment.user = request.user
            Payment.save()
            return redirect('home')
    else:
        form = PaymentForm()
    
    return render(request, 'pages/payment_form.html', {'form': form})

@login_required
def view_payments(request):
    user_payments = Payment.objects.filter(user=request.user)
    return render(request, 'pages/view_payments.html', {'user_payments': user_payments})

#CUSTOMER INFO
@login_required
def customer_details_view(request):
    if request.method == 'POST':
        form = CustomerDetailsForm(request.POST)
        if form.is_valid():
            customer_details = form.save(commit=False)
            customer_details.user = request.user
            customer_details.save()
            return redirect('payment_form') 
    else:
        form = CustomerDetailsForm()
    
    return render(request, 'pages/customer_details.html', {'form': form})

@login_required
def view_CustomerDetails(request):
    user_CustomerDetails = CustomerDetail.objects.filter(user=request.user)
    return render(request, 'pages/view_customerDetails.html', {'user_CustomerDetails': user_CustomerDetails})

#FEEDBACK
def feedback_form_view(request):
    if not request.user.is_authenticated:

        return redirect('login')
    else:
        if request.method == 'POST':
            form = FeedbackForm(request.POST)
            if form.is_valid():
                Feedback = form.save(commit=False)
                Feedback.user = request.user
                Feedback.save()
                return redirect('view_feedback')
        else:
            form = FeedbackForm()

        return render(request, 'pages/feedback_form.html', {'form': form})




def view_feedback(request):
    view_feedback = Feedback.objects.all()
    return render(request, 'pages/view_feedback.html', {'view_feedback': view_feedback})

webapp/templates/pages/about.html
{% extends 'pages/index.html' %}

{% block content %}

<!DOCTYPE html>
<html>
<head>
    <title>Twilight Terrace Hotel</title>
</head>
<body class="body-about">

    <div class="card">
        <div class="card-inner">
          <div class="card-front">
            <p>OUR MISSION</p>
          </div>
          <div class="card-back">
            <p class="mission">At Twilight Terrace Hotel, our mission is to provide an unparalleled guest experience by offering exceptional hospitality, personalized service, and a commitment to excellence. We strive to create a welcoming and comfortable environment that exceeds the expectations of every guest.</p>
          </div>
        </div>
      </div>
      <div class="card">
        <div class="card-inner">
          <div class="card-front">
            <p>CREATOR</p>
          </div>
          <div class="card-back">
            <p>Greetings! I'm [Your Name], a passionate [Your Profession or Role] with a zest for [Your Key Interests or Passions]. I thrive on [mention what motivates or inspires you in your field or life].</p>
          </div>
        </div>
      </div>
</body>
</html>

{% endblock %}

webapp/templates/pages/customer_details.html
{% extends 'pages/index.html' %}
{% load static%}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Customer Details Form</title>
</head>
<body>
    <div class="customer-details-form-container">
        <h1>Customer Details</h1>
        <form method="post" class="form-group">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit">
        </form>
    </div>
</body>
</html>

{% endblock %}

webapp/templates/pages/footer.html
{% load static%}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Footer</title>
</head>
<body>

</body>
</html>

webapp/templates/pages/home.html
{% extends 'pages/index.html' %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>CSS Template</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>


<div class="header">
  <h2>WELCOME TO OUR HOTEL</h2>
</div>

<div class="card">
  <p class="bg1"><span>SINGLE</span></p>
  <p class="bg2"><span>DOUBLE</span></p>
  <p class="bg3"><span>SUITE</span></p>
</div>


    <div class="card1">
        <p class="img1"></p>
        <p class="img2"></p>
    </div>
    <div class="card2">
        <p class="img3"></p>
        <p class="img4"></p>
    </div>
    <div class="card3">
        <p class="img5"></p>
        <p class="img6"></p>
    </div>


</body>
</html>



{% endblock %}

webapp/templates/pages/index.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>HOTEL</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static '/css/login.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/register.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/home.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/reservation.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/viewReservation.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/payment.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/viewPayment.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/customer.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/viewCustomer.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/feedback.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/viewFeedback.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/navbar.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/footer.css' %}">
    <link rel="icon" type="images/x-icon" href="{% static '/images/Logo-Trizia-removebg.png' %}">
</head>
 <body>
    {%include 'pages/navbar.html'%}

    {% block content %}
    
    {% endblock %}

    {%include 'pages\footer.html'%}

 </body>
</html>

webapp/templates/pages/login.html
{% extends 'pages/index.html' %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
</head>
<body>
    <div class="login-container">
        <form method="post" class="form-group">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Login">
        </form>
        <div class="register-link">
            <p>Don't have an account? <a href="{% url 'register' %}">Register here!</a></p>
        </div>
    </div>
</body>
</html>
{% endblock %}

webapp/templates/pages/navbar.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Navbar</title>
</head>
<body>
    <header class="navbar">
        <div class="logo">
            <img src="{% static 'images/Logo.png' %}" alt="">
        </div>
        <nav>
            <ul>
                <li><a href="{% url 'home' %}">Home</a></li>

                {% if user.is_authenticated %}
                    <li><a href="{% url 'reservation_form_view' %}">Reservation</a></li>
                    <li><a href="{% url 'view_appointments' %}">My Appointments</a></li>
                    <li><a href="{% url 'view_CustomerDetails' %}">My Details</a></li>
                    <li><a href="{% url 'view_feedback' %}">View Feedbacks</a></li>
                    <li><a href="{% url 'custom_logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">Login</a></li>
                    <li><a href="{% url 'view_feedback' %}">View Feedbacks</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
</body>
</html>

</html>

webapp/templates/pages/payment_form.html
{% extends 'pages/index.html' %}
{% load static%}

{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>Enter Payment Details</title>
</head>
<body>
    <div class="payment-form-container">
        <h1>Enter Payment Details</h1>
        <form method="post" class="form-group">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit Payment">
        </form>
    </div>
</html>

{% endblock %}

webapp/templates/pages/registration_form.html
{% extends 'pages/index.html' %}
{% load static%}

{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>Give Feedback</title>
</head>
<body>
    <div class="registration-container">
        <form method="post" class="form-group">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Register">
        </form>
    </div>
</body>
</html>
{% endblock %}

webapp/templates/pages/update_reservation.html
{% extends 'pages/index.html' %}
{% load static%}

{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>Create Reservation</title>
</head>
<body>
    <div class="reservation-form-container">
        <h1>Create Reservation</h1>
        <form method="post" class="form-group">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit Reservation">
        </form>
    </div>
</body>
</html>
{% endblock %}

webapp/templates/pages/view_customerDetails.html
{% extends 'pages/index.html' %}
{% load static %}

{% block content %}
<div class="center-container">
    <div class="customer-details">
        {% if user_CustomerDetails %}
            <h2>My Details</h2>
            <ul>
                {% for CustomerDetail in user_CustomerDetails %}
                    <li>First name: {{ CustomerDetail.first_name }} </li><br>
                    <li>Last name: {{ CustomerDetail.last_name }} </li><br>
                    <li>My address: {{ CustomerDetail.address }} </li><br>
                    <li>My phone number: {{ CustomerDetail.phone_number }} </li><br>
                    <li>Email: {{ CustomerDetail.email }}</li><br>
                {% endfor %}
            </ul>
            <a href="{% url 'view_payments' %}">View my Payment Details</a>
        {% else %}
            <p>No details found.</p>
        {% endif %}
    </div>
</div>
{% endblock %}

webapp/templates/pages/view_feedback.html
{% extends 'pages/index.html' %}
{% load static %}

{% block content %}

<div class="feedback-list">
    <h1>All Feedbacks</h1>
    {% if view_feedback %}
        <ul>
            {% for Feedback in view_feedback %}
                <li>
                    Name: {{ Feedback.user }}<br>
                    Comments: {{ Feedback.comments }}<br>
                    Rating: {{ Feedback.rating }}<br>
                </li>
            {% endfor %}
        </ul>
        <a href="{% url 'feedback_form' %}">Write a feedback</a>
    {% else %}
        <p>No feedbacks yet</p>
    {% endif %}
</div>
{% endblock %}

webapp/templates/pages/view_payments.html
{% extends 'pages/index.html' %}
{% load static %}

{% block content %}
<div class="center-container">
    <div class="payment-details">
        {% if user_payments %}
            <h2>My Payment Details</h2>
            <ul>
                {% for Payment in user_payments %}
                    <li>Card Number: {{ Payment.card_number }} </li><br>
                    <li>Card Expiry: {{ Payment.card_expiry }} </li><br>
                    <li>Card CVV: {{ Payment.card_cvv }} </li><br>
                {% endfor %}
            </ul>
            <a href="{% url 'view_CustomerDetails' %}" class="back-link">Back</a>
        {% else %}
            <p>No details found.</p>
        {% endif %}
    </div>
</div>
{% endblock %}

webapp/templates/pages/view_reservations.html
{% extends 'pages/index.html' %}
{% load static %}

{% block content %}
<div class="center-container">
    <div class="reservation-list">
        {% if user_reservations %}
            <h2>Your Reservations</h2>
            <ul>
                {% for reservation in user_reservations %}
                    <li>
                        Reservation ID: {{ reservation.id }} <br>
                        Check-in Date: {{ reservation.check_in_date }} <br>
                        Check-out Date: {{ reservation.check_out_date }} <br>
                        Room Type: {{ reservation.get_room_type_display }} <br>
                        Number of Guests: {{ reservation.num_guests }} <br>
                        <a href="{% url 'update_reservation' reservation.id %}">Update</a>
                        <form action="{% url 'cancel_reservation' reservation.id %}" method="post">
                            {% csrf_token %}
                            <input type="submit" value="Cancel">
                        </form>
                    </li>
                    <hr>
                {% endfor %}
            </ul>
        {% else %}
            <p>No reservations found.</p>
        {% endif %}
    </div>
</div>
{% endblock %}